version: "3.9"

services:

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./sql:/docker-entrypoint-initdb.d/"
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change_me
  
  metabase:
    depends_on:
      - postgres
    image: metabase/metabase:v0.45.2.1
    ports:
      - "3000:3000"
    restart: always
    environment:
      # JAVA_TIMEZONE: GMT
      MB_ENCRYPTION_SECRET_KEY: ${MB}
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: db
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: change_me
      MB_DB_HOST: postgres

  # pgadmin:
  #   depends_on:
  #     - postgres
  #   image: dpage/pgadmin4
  #   ports:
  #     - "3001:80"
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: timolin@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

volumes:
  pgdata:
